[workspace]
members = [ "example", "tlv",
    "tlv-derive"
]

[workspace.dependencies]
thiserror = "2.0.11"
syn = "2.0"
prettyplease = "0.2"
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0.4"
bytes = "1.9.0"
anyhow = "1.0.94"
